# Generated by Django 3.1.2 on 2021-05-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210526_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus_model',
            name='col_count',
        ),
        migrations.RemoveField(
            model_name='bus_model',
            name='row_count',
        ),
        migrations.AddField(
            model_name='bus_model',
            name='place_count',
            field=models.IntegerField(default=0, verbose_name='Мест'),
        ),
    ]
